#!/bin/sh

eval `xinput list | grep -oP 'Touchpad\K.*id=\d*'`

state=$(xinput list-props $id | grep "Device Enabled" | awk '{print $NF}')

[ ! -n "${id}" ] && exit 1

if [ "${state}" -eq '1' ]; then
	dunstify -r 19 -a center --timeout=1500 -i "$pOS_NOTIF_IMG_DIR/touchpad-disabled.png" ""
	xinput set-prop $id "Device Enabled" 0
else
	dunstify -r 19 -a center --timeout=1500 -i "$pOS_NOTIF_IMG_DIR/touchpad-enabled.png" ""
	xinput set-prop $id "Device Enabled" 1
fi
