#!/bin/sh

pOS_NOTIF_IMGS="/usr/share/phyos/notification-imgs/"


id=$(xinput list | grep Touchpad | awk '{ print $6}' | cut -d '=' -f 2)

state=$(xinput list-props $id | grep "Device Enabled" | awk ' {print $4} ')

if [ $state = 1 ]; then
	dunstify -r 19 -a center -i "$pOS_NOTIF_IMGS/touchpad-disabled.png" ""
	xinput set-prop $id "Device Enabled" 0
else
	dunstify -r 19 -a center -i "$pOS_NOTIF_IMGS/touchpad-enabled.png" ""
	xinput set-prop $id "Device Enabled" 1
fi
